import random
from Implementations.PA_11 import get_group

# =====================================================================
# 1. CORE ELGAMAL CRYPTOSYSTEM LOGIC
# =====================================================================

def elgamal_keygen(group_size="large"):
    """
    Key Generation for ElGamal.
    Returns: (sk, pk) where sk=x, pk=(p, g, q, h)
    """
    p, g, q = get_group(group_size)
    # 1. Sample private key x from Zq
    x = random.randint(1, q - 1)
    
    # 2. Compute public key h = g^x mod p
    h = pow(g, x, p)
    
    sk = x
    pk = (p, g, q, h)
    return sk, pk

def Enc(pk: tuple, m: int) -> tuple[int, int]:
    """
    Encryption of m in G.
    Returns: (c1, c2) = (g^r mod p, m * h^r mod p)
    """
    p, g, q, h = pk
    
    # 1. Sample fresh r in Zq
    r = random.randint(1, q - 1)
    
    # 2. Output C = (c1, c2)
    c1 = pow(g, r, p)
    c2 = (m * pow(h, r, p)) % p
    
    return c1, c2

def Dec(sk: int, pk: tuple, c1: int, c2: int) -> int:
    """
    Decryption of (c1, c2).
    Returns: m = c2 / c1^x mod p
    """
    p, g, q, h = pk
    x = sk
    
    # Compute the inverse of c1^x mod p
    s = pow(c1, x, p)
    s_inv = pow(s, -1, p)
    
    # m = c2 * s^{-1} mod p
    m = (c2 * s_inv) % p
    return m

# =====================================================================
# 2. ATTACK DEMONSTRATIONS
# =====================================================================

def malleability_attack(pk: tuple, c1: int, c2: int, multiplier: int):
    """
    Given ciphertext (c1, c2) for unknown m, construct (c1, multiplier * c2 mod p)
    which decrypts to multiplier * m.
    """
    p, g, q, h = pk
    new_c2 = (multiplier * c2) % p
    return c1, new_c2

def demo_malleability():
    """
    Demonstrate that multiplying c2 by 2 results in 2m after decryption.
    """
    print("\n--- Malleability Attack Demo ---")
    sk, pk = elgamal_keygen()
    m = 42 # Plaintext message
    
    print(f"Original plaintext message: {m}")
    c1, c2 = Enc(pk, m)
    print(f"Ciphertext: (c1, c2) = ({c1}, {c2})")
    
    # Attack: without knowing x or m
    tampered_c1, tampered_c2 = malleability_attack(pk, c1, c2, 2)
    print(f"Adversary tampers with ciphertext -> (c1, 2*c2 mod p)")
    
    # Decrypt intercepted tampered ciphertext
    recovered_m = Dec(sk, pk, tampered_c1, tampered_c2)
    print(f"Decrypted tampered message: {recovered_m}")
    
    if recovered_m == (2 * m) % pk[0]:
        print("[!] ADVERSARY WINS: The scheme is completely malleable!")
    else:
        print("Failure in malleability attack.")

def ind_cpa_game(group_size="large"):
    """
    Implement the IND-CPA game for ElGamal.
    """
    print(f"\n--- IND-CPA Game Simulation ({group_size} group) ---")
    sk, pk = elgamal_keygen(group_size)
    p, g, q, h = pk
    
    # Choose two distinct messages m0, m1 in the group
    # We must ensure they are in the subgroup generated by g
    m0 = pow(g, 123, p)
    m1 = pow(g, 456, p)
    
    # Challenge phase
    b = random.choice([0, 1])
    mb = m0 if b == 0 else m1
    c1_star, c2_star = Enc(pk, mb)
    
    # If the group is tiny (e.g., q ~ 2^10), the adversary can use brute force / discrete log
    guess_b = None
    if group_size == "tiny":
        print(f"Tiny group detected! Adversary initiates Discrete Log brute-force on h = g^x...")
        # Since q is small, an adversary can exhaustively find x
        x_recovered = None
        for i in range(1, q):
            if pow(g, i, p) == h:
                x_recovered = i
                break
        
        if x_recovered is not None:
            # Decrypt the challenge directly
            decrypted_mb = Dec(x_recovered, pk, c1_star, c2_star)
            if decrypted_mb == m0:
                guess_b = 0
            else:
                guess_b = 1
            print("Adversary found x via brute force!")
    else:
        print("Large group detected. Adversary guesses randomly...")
        guess_b = random.choice([0, 1])

    print(f"Adversary guessed: {guess_b}, Actual: {b}")
    
    if guess_b == b:
        if group_size == "tiny":
            print("[!] TINY GROUP WIN: Distinguisher effectively recovered the message.")
        else:
            print("Adversary was just lucky. (Advantage ~ 0 in large group)")
    else:
        print("Adversary failed. CPA security holds under DDH (Large group).")

if __name__ == "__main__":
    demo_malleability()
    ind_cpa_game("large")
    ind_cpa_game("tiny")
